# Generated by Django 5.0.1 on 2024-04-22 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("d007f9ac-7aa5-43a5-b57c-078890c73458"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("637429b5-799b-42e7-af80-d48c0316aacf"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("d940c53e-67cc-4bd4-9a07-df787d1632cb"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("144f46be-f563-40cd-a640-886cc55e3401"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("e4d970de-5c16-4e95-9593-e4d454dc3436"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="FarmNPKLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("f6c1da4b-eb41-4330-abd1-07fc93dc8c4c"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("n", models.CharField(max_length=20)),
                ("p", models.CharField(max_length=20)),
                ("k", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_npk_link_farm",
                        to="dashboard.farm",
                    ),
                ),
            ],
            options={
                "db_table": "farm_npk_link",
            },
        ),
    ]
