# Generated by Django 5.0.1 on 2024-01-29 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("2ba0adb4-d88b-4fbb-bbc1-eec934e02bd5"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("dce165a2-50fb-4dd9-b1f9-c8aa6aaa211e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("0074ea27-b0ea-407a-b760-d3427400bde4"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("ba158068-288b-4944-b6f0-d0b260dd8ab1"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("0e4fdaad-abe7-4cab-a3af-5833417a2f99"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="k",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="n",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="p",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="time_required",
            field=models.CharField(max_length=100),
        ),
    ]
