# Generated by Django 5.0.1 on 2024-01-31 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_farm_id_alter_farmvegetablelink_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("3c8e89e9-974a-4c92-8269-bbebd1e69e55"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a9a9f771-4a40-4e67-90e9-5aec59f000e5"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("7c57be8d-3e9f-4df4-b4c9-457fce1dbecf"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("e687bf20-a1ea-4e0f-88ac-e523f65e5a64"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("ca18d2a0-d8fc-41fd-b5f2-499524b9decd"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
