# Generated by Django 5.0.1 on 2024-01-16 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_user_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9de6e4f9-8815-4a7a-8c16-37cd6223c529"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
