# Generated by Django 5.0.1 on 2024-01-31 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_userfarmlink_is_completed_alter_farm_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmvegetablelink",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a1375c98-73bf-4bd9-945a-573c4b194415"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a605950c-7b38-4f93-afd2-1a86ba042152"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("3d86fd08-33b6-43ee-bbc4-dbac2ce81c68"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("e383d5c3-c27a-4ea9-a844-6ffb2dcfe87f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("cba43078-6b14-4ef0-81f5-c602a5120bfd"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
