# Generated by Django 5.0.1 on 2024-01-17 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_user_phone_alter_user_email_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("5be384ff-08be-447c-a003-87c870ab19f6"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
