# Generated by Django 5.0.1 on 2024-04-19 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_user_is_admin_alter_farm_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("d7ad46b8-1d3a-4d81-acd9-764dbd9deaf9"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("eb570f2f-136b-46d8-908f-0cee421952f5"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("8179fbdc-0aae-4ab9-94a5-ad4d01efc847"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("5888a66e-4a8f-43de-98fc-08318d2a30c2"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("91040553-c2b8-4b34-9176-823d572fcf4f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
