# Generated by Django 5.0.1 on 2024-01-17 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_alter_user_id_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("888cd26c-88a4-4db7-b186-d35c14b0ce2f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
