# Generated by Django 5.0.1 on 2024-01-18 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_farm_description_alter_farm_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9064716f-40ea-4434-9717-b1f9969d06b5"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("98f7616d-e2e5-48dd-b8ac-5faa95279570"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="UserFarmLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("c2ab0efe-711e-4ed7-a8b2-0d6728fce964"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_farm_link_farm",
                        to="dashboard.farm",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_farm_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_farm_link",
            },
        ),
    ]
