# Generated by Django 5.0.1 on 2024-01-18 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_alter_farm_id_alter_user_id_userfarmlink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfarmlink",
            old_name="farm_id",
            new_name="farm",
        ),
        migrations.RenameField(
            model_name="userfarmlink",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9ae04460-72e7-42fa-b0d3-69d447619259"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a1d10810-6449-4525-82ad-d33fb59ba557"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("7204dec2-b1c4-47df-8497-f87c7bab755c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
