# Generated by Django 5.0.1 on 2024-01-26 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_vegetable_alter_farm_id_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("1a69a2b6-a3e9-4b21-897c-1603be1d315d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("83d87811-b772-46dc-af0c-3ccce20a0690"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("d5d56b9c-4adf-43ae-b73e-1a30db05be3c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("6ce08bde-9940-448f-83d2-a381df9258d1"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
