# Generated by Django 5.0.1 on 2024-01-26 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_user_profile_pic_alter_farm_id_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a46d62df-bcd2-4c0e-9441-ece202eba093"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("eece6f9c-fa09-4ea8-b2a2-d5a1d6cc310e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="user"),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("438d1ac5-7cad-40ee-940d-f7296c108b7f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("3f98f0b4-6a42-4f0f-a3d4-0a50ece15c52"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
