# Generated by Django 5.0.1 on 2024-01-26 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0018_alter_farm_id_alter_user_id_alter_user_profile_pic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("4035fd56-ecf1-4771-ae84-c69d4e726d55"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("ecfe5124-5c58-49db-af2b-9aa138b9fe6e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="user"
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("e86449fe-d48b-4027-a079-7e560d5512ec"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("6f8609fb-674f-4101-93d7-8d3a928982ce"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
