# Generated by Django 5.0.1 on 2024-01-26 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0020_alter_farm_id_alter_user_id_alter_userfarmlink_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("5db9fcf5-a3d2-4a2c-b9ca-7994584e9e85"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("caf624b4-0382-482c-bfee-5f7421aff7b0"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("5b77202d-2710-4f71-a8a5-f9d7698173d1"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("23d1dd3d-2e62-4e6e-9f67-46567419929e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
