# Generated by Django 5.0.1 on 2024-01-26 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0022_alter_farm_id_alter_user_id_alter_user_profile_pic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("e42f1e64-dec3-41e7-a390-1ddef9e1fd52"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9deb0c93-ffcc-43b1-9425-7e1f4ec07f9c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a5f9d0fd-172d-4ebf-a74b-738376c7be2d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("f489ab5b-1966-497e-bf02-bd5ed9bbb186"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
