# Generated by Django 5.0.1 on 2024-01-28 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0023_farm_location_alter_farm_id_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vegetable",
            name="k",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vegetable",
            name="n",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vegetable",
            name="p",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vegetable",
            name="time_required",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("94c9c691-78be-4bbb-a742-eff77548e3d5"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("cfca514a-3400-4315-8f73-e3674ac77c6f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("0c76f01f-1cef-4ee5-89c5-0c90f8e1a816"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9d517733-978c-4c53-a809-ed9ab76d9519"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
