# Generated by Django 5.0.1 on 2024-01-28 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0024_vegetable_k_vegetable_n_vegetable_p_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("66cf2728-d231-44f5-a010-245cb2d26292"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a5a749ef-d919-429e-bc3d-bc3e610ce48f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("cbdd8f66-42cd-4773-b08a-584123236072"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("1c6abdde-db32-45c0-8cd4-6f2d46d6a9ea"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="k",
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="n",
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="p",
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="time_required",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
