# Generated by Django 5.0.1 on 2024-01-28 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0025_alter_farm_id_alter_user_id_alter_userfarmlink_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9a27fa3d-8542-4494-b1dd-f00d3341ff69"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9c32f31c-ea2c-48bf-80f5-44a17ce4a820"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("bb4b80f5-5beb-4573-b986-adda7d549ff6"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("65d124c8-7605-482e-8c6e-9a5a43ca305d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="FarmVegetableLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("862f4683-8ce6-455a-8357-4b9f901859b9"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_vegetable_link_farm",
                        to="dashboard.farm",
                    ),
                ),
                (
                    "vegetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_vegetable_link_vegetable",
                        to="dashboard.vegetable",
                    ),
                ),
            ],
        ),
    ]
