# Generated by Django 5.0.1 on 2024-01-28 06:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0026_alter_farm_id_alter_user_id_alter_userfarmlink_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("529f2ac0-68ee-4aaa-80b4-76cf3a9c0822"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9cc19702-71d9-4081-af5c-0861d406a83d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("500307c4-0c80-4122-9cc3-7fd9179d851a"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("c9fd2819-b281-41f2-bb5f-cc7b43ad6d74"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("d33b9e52-f468-4830-a178-f9c5dc27ba7e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="farmvegetablelink",
            table="farm_vegetable_link",
        ),
    ]
