# Generated by Django 5.0.1 on 2024-01-29 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0027_alter_farm_id_alter_farmvegetablelink_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("80c6c28e-3b3d-4f9a-9513-ca49ec6a4b22"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("bf4fd206-6228-45e8-a1ba-ca69e4073be6"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("16cf1c08-c286-4347-94e2-ebf1e624a1ce"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("232fe485-4014-4a3b-aec7-93d70918b4cf"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("b9ad023b-3987-456f-9947-1e5d4c1bb84d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
