# Generated by Django 5.0.1 on 2024-01-29 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0030_alter_farm_id_alter_farmvegetablelink_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("cdb98c48-cbeb-452a-b2d6-01bae87addc4"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("2fa03b71-369e-4d6b-b6f4-b34d4eba0fda"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("4dcd9d16-5c60-4d88-87b7-8ff2dc9ef690"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("884e1d48-32d8-4488-ad81-f9310c86ec4c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("9ad9e4ef-b3e9-43bf-abc1-4b7c6f5dc19d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
