# Generated by Django 5.0.1 on 2024-01-29 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0034_alter_farm_id_alter_farmvegetablelink_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.CharField(
                default=uuid.UUID("04e2e2b4-b216-4522-ae7a-aa88e1d6fa7f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="farmvegetablelink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("db6e4a3f-9fbf-486b-a2d7-9a78073b870d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("63b9eef9-5a79-48a1-8b18-3a86786d3257"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userfarmlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("951ddb69-60e5-432b-9cc7-4e95fadcb2de"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vegetable",
            name="id",
            field=models.CharField(
                default=uuid.UUID("8389fb15-c95b-4d1c-aed1-f0fe0d2ffcd6"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
